#!/bin/bash
# Builds two apps into the parent folder (your Applications folder):
#   Charopos.app        - runs on the server; local UI + remote API
#   Charopos Remote.app - copy to another Mac; controls the server
# Requires Xcode (run once: sudo xcode-select -s /Applications/Xcode.app)
#
# NOTE: the embedded scripts are copies made at build time. After editing a
# .command file, re-run this script so the app picks up the changes.
set -euo pipefail
cd "$(dirname "$0")"

# ---------------------------------------------------------------- version
MAJOR=4
MINOR_FILE="version_minor.txt"
MINOR=0
if [[ -f "$MINOR_FILE" ]]; then
    PREV=$(tr -cd '0-9' < "$MINOR_FILE")   # digits only: junk in the file would abort the arithmetic under set -e
    MINOR=$(( ${PREV:--1} + 1 ))
fi
echo "$MINOR" > "$MINOR_FILE"
BUILD_DATE=$(date +%y%m%d)
VERSION="${MAJOR}.${MINOR}.${BUILD_DATE}"
echo "Version: $VERSION"

# Write Version.swift — compiled into both apps
cat > Version.swift <<SWIFTEOF
// Auto-generated by build.sh — do not edit
let appVersion = "${VERSION}"
SWIFTEOF

# Stamp version into both Info.plist files
# Short version = "4.35"; build number = "260701" → About shows "Version 4.35 (260701)"
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${MAJOR}.${MINOR}" Info.plist
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${BUILD_DATE}" Info.plist
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${MAJOR}.${MINOR}" Info-Remote.plist
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${BUILD_DATE}" Info-Remote.plist

APP="../Charopos.app"
REMOTE_APP="../Charopos Remote.app"

# Source-of-truth scripts: prefer the user's "../Original Scripts" (personal copies,
# never modified by the build), else the committed generic reference scripts in
# ./Scripts (so a fresh clone builds and a stranger gets working actions out of the box).
if [[ -d "../Original Scripts" ]]; then
  SCRIPTS_FROM="../Original Scripts"
else
  SCRIPTS_FROM="Scripts"
fi
echo "Embedding scripts from: $SCRIPTS_FROM"

# ---------------------------------------------------------------- icon
ICON_TMP=""
if [[ -f AppIcon.png ]]; then
  echo "Generating app icon from AppIcon.png..."
  rm -rf AppIcon.iconset
  mkdir AppIcon.iconset
  for size in 16 32 128 256 512; do
    sips -s format png -z $size $size AppIcon.png --out "AppIcon.iconset/icon_${size}x${size}.png" >/dev/null
    sips -s format png -z $((size*2)) $((size*2)) AppIcon.png --out "AppIcon.iconset/icon_${size}x${size}@2x.png" >/dev/null
  done
  ICON_TMP="$(mktemp -d)/AppIcon.icns"
  iconutil -c icns AppIcon.iconset -o "$ICON_TMP"
  rm -rf AppIcon.iconset
else
  echo "Note: no AppIcon.png in this folder; building without a custom icon."
fi

install_icon() {  # $1 = app bundle path
  if [[ -n "$ICON_TMP" && -f "$ICON_TMP" ]]; then
    cp "$ICON_TMP" "$1/Contents/Resources/AppIcon.icns"
    cp AppIcon.png "$1/Contents/Resources/AppIcon.png"
    [[ -f AppIconArtwork.png ]] && cp AppIconArtwork.png "$1/Contents/Resources/AppIconArtwork.png"
  fi
  for col in green red orange blue grey; do
    [[ -f "menubar-icon-${col}.png" ]]       && cp "menubar-icon-${col}.png"       "$1/Contents/Resources/menubar-icon-${col}.png"
    [[ -f "menubar-icon-${col}-light.png" ]] && cp "menubar-icon-${col}-light.png" "$1/Contents/Resources/menubar-icon-${col}-light.png"
  done
}

# ------------------------------------------------------------- compilation
# swiftc emits one architecture at a time, so a universal binary means building
# each slice and lipo-ing them together. Worth it because "Charopos Remote.app"
# is meant to be copied to another Mac, which may well be Intel.
# The deployment target matches LSMinimumSystemVersion in both Info.plists.
DEPLOY_TARGET="13.0"
ARCHS=(arm64 x86_64)

build_universal() {   # $1 = output binary path, $2... = source files
  local out="$1"; shift
  local slices=()
  for arch in "${ARCHS[@]}"; do
    echo "  - ${arch}"
    xcrun swiftc -O -parse-as-library \
      -target "${arch}-apple-macos${DEPLOY_TARGET}" \
      "$@" -o "${out}-${arch}"
    slices+=("${out}-${arch}")
  done
  lipo -create "${slices[@]}" -output "$out"
  rm -f "${slices[@]}"
}

# ---------------------------------------------------------------- server app
echo "Compiling server app sources..."
build_universal Charopos \
  Models.swift Runner.swift APIServer.swift ContentView.swift PreferencesView.swift OnboardingView.swift HelpView.swift App.swift \
  Version.swift

echo "Assembling Charopos.app..."
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources/scripts"
mv Charopos "$APP/Contents/MacOS/Charopos"
cp Info.plist "$APP/Contents/Info.plist"

echo "Embedding scripts..."
# Auto-embed every .command/.sh in the source folder. A missing script degrades
# gracefully (its action simply has nothing to run) rather than hard-failing the build.
found=0
while IFS= read -r -d $'\0' src; do
  fname="$(basename "$src")"
  cp "$src" "$APP/Contents/Resources/scripts/"
  chmod +x "$APP/Contents/Resources/scripts/$fname"
  echo "  + $fname"
  (( found++ )) || true
done < <(find "$SCRIPTS_FROM" -maxdepth 1 -type f \( -name "*.command" -o -name "*.sh" \) -print0)
[[ $found -gt 0 ]] || echo "WARNING: no .command/.sh files found in $SCRIPTS_FROM" >&2

echo "Embedding web dashboard..."
sed "s/__DASHBOARD_VERSION__/${VERSION}/g" dashboard.html > "$APP/Contents/Resources/dashboard.html"

install_icon "$APP"
codesign --force --sign - "$APP"
echo "Built: Charopos.app"

# ---------------------------------------------------------------- remote app
echo "Compiling RemoteLauncher.swift..."
build_universal CharoposRemote RemoteLauncher.swift Version.swift

echo "Assembling Charopos Remote.app..."
rm -rf "$REMOTE_APP"
mkdir -p "$REMOTE_APP/Contents/MacOS" "$REMOTE_APP/Contents/Resources"
mv CharoposRemote "$REMOTE_APP/Contents/MacOS/CharoposRemote"
cp Info-Remote.plist "$REMOTE_APP/Contents/Info.plist"

install_icon "$REMOTE_APP"
codesign --force --sign - "$REMOTE_APP"
echo "Built: Charopos Remote.app"

[[ -n "$ICON_TMP" ]] && rm -rf "$(dirname "$ICON_TMP")"
rm -f Version.swift
echo "Done. Built version ${VERSION}."
